/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf 
Author: moyicat (https://sketchfab.com/moyicat)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/room-01-magicavoxel-cbebf8f78edb4f80ac18b54f6771a90b
Title: Room 01 / MagicaVoxel
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function MyRoomModel1(props) {
  const { nodes, materials } = useGLTF('models/myRoom_model1/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials['Scene_-_Root']}
          position={[-16, -16, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/myRoom_model1/scene.gltf')
