/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf 
Author: moyicat (https://sketchfab.com/moyicat)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/room-04-magicavoxel-27c20a0a51124f9c883c080f3323ea04
Title: Room 04 /  MagicaVoxel
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function MyRoomModel3(props) {
  const { nodes, materials } = useGLTF('models/myRoom_model3/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials['Scene_-_Root']}
          position={[-32, -32, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/myRoom_model3/scene.gltf')
